### ISSUE TITLE
Convert to kotlin

### ISSUE THREAD

**Issue by ericlewis** [ericlewis/react-native-contact-tracing#13]
redo the android stub with Kotlin

**Comment by Krizzu** [comment]
Hey, Sign me up :)

**Comment by ericlewis** [comment]
@Krizzu thank you! Assigned to you :)

**Comment by Krizzu** [comment]
@ericlewis I'd also setup Android example as part of upcoming PR, WDYT?

**Comment by ericlewis** [comment]
@Krizzu that would be awesome too. I will add you to that ticket as well.

**Comment by ericlewis** [comment]
resolved! thanks @Krizzu
