### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by artmerlop** [ericlewis/react-native-contact-tracing#20]

**Comment by ericlewis** [comment]
@artmerlop it is not, I am updating things now.

**Comment by artmerlop** [comment]
@ericlewis great!

**Comment by artmerlop** [comment]
@ericlewis are you releasing this updates today?

**Comment by ericlewis** [comment]
@artmerlop Over the next week, for iOS at least. I’ve only now had the time to update to Xcode 13.5.
